---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:8080/api/v1
  APP_URL: http://localhost:3000
  SESSION_SECRET: supersecret

test:
  API_URL: http://localhost:8080/api/v1
  APP_URL: http://localhost:3000
  SESSION_SECRET: supersecret
